Go
CREATE TABLE NHAN_VIEN (
    MA_NV VARCHAR(20) PRIMARY KEY,
    TEN_NV NVARCHAR(100) NOT NULL,
    DIA_CHI NVARCHAR(200)
);
CREATE TABLE QUA_TRINH_TANG_LUONG (
    MA_NV VARCHAR(20) NOT NULL,
    NGAY_HIEU_LUC DATE NOT NULL,
    LUONG_MOI DECIMAL(18, 2) NOT NULL,
    PRIMARY KEY (MA_NV, NGAY_HIEU_LUC),
    FOREIGN KEY (MA_NV) REFERENCES NHAN_VIEN(MA_NV) ON DELETE CASCADE
);
CREATE TABLE NV_KINH_DOANH (
    MA_NV VARCHAR(20) PRIMARY KEY,
    FOREIGN KEY (MA_NV) REFERENCES NHAN_VIEN(MA_NV) ON DELETE CASCADE
);
CREATE TABLE NV_KD_LAU_NAM (
    MA_NV VARCHAR(20) PRIMARY KEY,
    FOREIGN KEY (MA_NV) REFERENCES NV_KINH_DOANH(MA_NV) ON DELETE CASCADE
);
CREATE TABLE NV_KD_TAP_SU (
    MA_NV VARCHAR(20) PRIMARY KEY,
    MA_NV_HUONG_DAN VARCHAR(20) NULL,
    FOREIGN KEY (MA_NV) REFERENCES NV_KINH_DOANH(MA_NV) ON DELETE CASCADE,
    FOREIGN KEY (MA_NV_HUONG_DAN) REFERENCES NV_KD_LAU_NAM(MA_NV) ON DELETE NO ACTION
);
CREATE TABLE DON_HANG (
    SO_DOH VARCHAR(20) PRIMARY KEY,
    KHACH_HANG NVARCHAR(100) NOT NULL,
    TRI_GIA DECIMAL(18, 2) NOT NULL DEFAULT 0
);
CREATE TABLE THUONG_LUONG (
    MA_NV VARCHAR(20) NOT NULL,
    SO_DOH VARCHAR(20) NOT NULL,
    HOA_HONG DECIMAL(18, 2) NOT NULL DEFAULT 0,
    PRIMARY KEY (MA_NV, SO_DOH),
    FOREIGN KEY (MA_NV) REFERENCES NV_KINH_DOANH(MA_NV) ON DELETE CASCADE,
    FOREIGN KEY (SO_DOH) REFERENCES DON_HANG(SO_DOH) ON DELETE CASCADE
);
INSERT INTO NHAN_VIEN (MA_NV, TEN_NV, DIA_CHI) VALUES 
('NV01', N'Nguyễn Văn A', N'Hà Nội'),
('NV02', N'Trần Thị B', N'TP.HCM');

INSERT INTO QUA_TRINH_TANG_LUONG (MA_NV, NGAY_HIEU_LUC, LUONG_MOI) VALUES 
('NV01', '2025-01-01', 15000000),
('NV01', '2026-01-01', 18000000);

INSERT INTO NV_KINH_DOANH (MA_NV) VALUES ('NV01'), ('NV02');
INSERT INTO NV_KD_LAU_NAM (MA_NV) VALUES ('NV01');
INSERT INTO NV_KD_TAP_SU (MA_NV, MA_NV_HUONG_DAN) VALUES ('NV02', 'NV01');

INSERT INTO DON_HANG (SO_DOH, KHACH_HANG, TRI_GIA) VALUES 
('DH01', N'Công ty X', 50000000);

INSERT INTO THUONG_LUONG (MA_NV, SO_DOH, HOA_HONG) VALUES 
('NV01', 'DH01', 2500000);


-- Xem thông tin nhân viên kinh doanh
SELECT nv.MA_NV, nv.TEN_NV, nv.DIA_CHI
FROM NHAN_VIEN nv
INNER JOIN NV_KINH_DOANH nvkd ON nv.MA_NV = nvkd.MA_NV;

-- Xem nhân viên tập sự và người hướng dẫn
SELECT 
    ts.MA_NV AS Ma_TapSu, 
    nv_ts.TEN_NV AS Ten_TapSu,
    ts.MA_NV_HUONG_DAN AS Ma_HuongDan,
    nv_hd.TEN_NV AS Ten_HuongDan
FROM NV_KD_TAP_SU ts
JOIN NHAN_VIEN nv_ts ON ts.MA_NV = nv_ts.MA_NV
LEFT JOIN NHAN_VIEN nv_hd ON ts.MA_NV_HUONG_DAN = nv_hd.MA_NV;

-- Xem tổng hoa hồng theo từng đơn hàng (Đã sửa lỗi bảng NHAN_VIEN)
SELECT dh.SO_DOH, dh.KHACH_HANG, nv.TEN_NV, tl.HOA_HONG
FROM DON_HANG dh
JOIN THUONG_LUONG tl ON dh.SO_DOH = tl.SO_DOH
JOIN NHAN_VIEN nv ON tl.MA_NV = nv.MA_NV;